---
- name: Transfer and execute a script.
  hosts: utility
  remote_user: pbhagavathula
  sudo: yes
  tasks:
     - name: check auditd status
       shell: service openvas-manager status
       
     - name: check auditd status
       shell: service openvas-scanner status
